/** Declaration file generated by dts-gen */

export const bodyParser: any[];

export function create(): void;

export function defaults(opts: any): any;

export function rewriter(routes: any): any;

export function router(source: any, opts?: any): any;

export namespace defaults {
  const prototype: {};
}
